### ISSUE TITLE
Library crashes in SHA1.c in 64 bit architecture

### ISSUE THREAD

**Issue by adnan-infinione** [contextio/contextio-ios#1]
App crashes at this point  memcpy(&context->buffer[j], data, (i = 64-j)); in SHA1.c  Perhaps if we increase size of buffer from 64 to 128, App does not crash but context.io sends following error.

error creating connect token: Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299), got 401" UserInfo=0x109d31280 {NSLocalizedRecoverySuggestion={"type":"error","code":105,"value":"Invalid signature kubK2V\/fsdfstrHugJGGGgVHh=. Signature base string should be POST&https%3A%2F%2Fapi.context.io%2F2.0%2Fconnect_tokens&callback_url%3Dcio-api.........

**Comment by Pretz** [comment]
Version 0.9.0 of this library uses a better [OAuth library](https://github.com/tweetdeck/TDOAuth) that is fully 64bit compatible. Please let me know if you have any trouble with the new version!

**Comment by adnan-infinione** [comment]
Thanks.
