### ISSUE TITLE
Rewrite in Swift

### ISSUE THREAD

**Issue by istx25** [contextio/contextio-ios#2]
I am not sure who I should be contacting regarding this, but hello! I've decided to throw up this Github issue and hopefully someone from ContextIO sees this. I'm working on a reimplementation of your API in Swift...cause I'm bored. :smile: 

I am wanting to push what I've been working on so far to a new branch here so while I'm working on it, others can pitch in as well. I do not want to create a PR request to the master branch, because no Objective C will be inside. Would someone create a swift branch so I can submit a PR and start the ball rolling for the Swift community? 

Thanks! Hope to hear back from someone.

**Comment by tonyblank** [comment]
Howdy! You are awesome!! I made a new repo for a Swift client lib. It's here - https://github.com/contextio/contextio-swift

I'm happy to collaborate with you on this! I haven't played with Swift yet, but have been wanting to!

Cheers,
Tony

**Comment by clooth** [comment]
What's going on with the Swift port?

**Comment by istx25** [comment]
@clooth: I am no longer working on this. I'd recommend contacting @tonyblank or someone on the Context.io team about writing your own or seeing if there is any progress elsewhere (like another community driven library).

**Comment by clooth** [comment]
Do you know where the repo is nowadays of the original swift port?

**Comment by istx25** [comment]
Seems like https://github.com/contextio/contextio-swift has been deleted so it no longer exists. It would've been Swift 1.1 code anyways so you might as well start from the ground up.
